Blazing Hawks
Clifford Jones\
Dongyu Liu\
Yuan Chen


**A.I. Disclaimer: Work for this assignment was completed with the aid of artificial intelligence tools.**





## Bisection Method

#### **Overview**  
Bisection Method is a numerical method used to find the roots of equations, based on the **Intermediate Value Theorem**.

#### **Steps**  
1. Choose an initial interval \([a, b]\) such that $( f(a) \cdot f(b) < 0 )$ (i.e., the function has a root within the interval).
2. Compute the midpoint $( c = \frac{a + b}{2} )$.
3. Evaluate \( f(c) \) and check:
   - If $( f(c) = 0 )$, then $( c )$ is the root, and the algorithm stops.
   - If $( f(a) \cdot f(c) < 0 )$, set $( b = c )$; otherwise, set $( a = c )$.
4. Repeat steps 2-3 until the error criterion is met.

#### **Advantages**  
- Guaranteed convergence if the initial interval is chosen correctly.  
- Simple and easy to implement.  

#### **Disadvantages**  
- Converges slowly, often requiring many iterations.  
- Only applicable to continuous functions and requires an initial interval containing a root.  

---

## Newton Method

#### **Overview**  
Newton Method is an iterative technique for approximating the roots of equations, based on **Taylor expansion** and **tangent approximation**.

#### **Steps**  
1. Select an initial guess $( x_0 )$.
2. Compute the iteration formula:
   $$
   x_{n+1} = x_n - \frac{f(x_n)}{f'(x_n)}
   $$
3. Update $( x_{n+1} )$ and repeat until the error criterion is met.

#### **Advantages**  
- Fast convergence (typically quadratic, meaning the error decreases quadratically).  
- Applicable to a wide range of nonlinear equations.  

#### **Disadvantages**  
- Requires the derivative $( f'(x) )$, which can be complex to compute.  
- May not converge or may oscillate/diverge if the initial guess is poorly chosen.  


#### **Multivariable Newton Method with Hessian Matrix**  
For functions with multiple variables, Newton's method extends using the **Hessian matrix**. The Hessian matrix \( H(x) \) is a square matrix of second-order partial derivatives, used to refine the root-finding process.

The iteration formula for a function $( f: \mathbb{R}^n \to \mathbb{R}^n )$ becomes:
   $$
   x_{n+1} = x_n - H(x_n)^{-1} \nabla f(x_n)
   $$
where:  
- $( \nabla f(x_n) )$ is the gradient vector (first-order partial derivatives).  
- $( H(x_n) )$ is the Hessian matrix (second-order partial derivatives).  

This method is particularly useful in **optimization problems**, where it helps find local minima or maxima efficiently. However, computing and inverting the Hessian matrix can be computationally expensive for high-dimensional problems.  




\
\
We first test these methods on a **single-variable function**, followed by **multi-variable cases**, including **linear and nonlinear functions**.

---

#### **1. Single Variable Case: Cube Root Function**
We start by testing **Bisection and Newton’s methods** using the cube root function:
$$
f(x) = \sqrt[3]{x}
$$
with first guess a = -1, b = 0.8




In [2]:
import numpy as np
import matplotlib.pyplot as plt


In [30]:


def f(x):
    # Cube root function, works for negative x too.
    return np.cbrt(x)


def bisection_method(a, b, tol=1e-8, max_iter=100):
    if f(a)*f(b) >= 0:
        print("Bisection method fails: f(a) and f(b) must have opposite signs.")
        return None
    print("\nBisection Method Iterations:")
    for i in range(max_iter):
        c = (a + b) / 2.0
        fc = f(c)
        if abs(fc) < tol or (b - a)/2 < tol:
            print("converged after", i, "iterations")
            return c
        if f(a)*fc < 0:
            b = c
        else:
            a = c
    return (a + b) / 2.0


# Bisection method: choose an interval that brackets the root.
a, b = -1, 0.8  # f(-1) = -1, f(1) = 1 so the sign change condition holds.
bisection_root = bisection_method(a, b)
print("\nBisection method result:", bisection_root)



Bisection Method Iterations:
converged after 27 iterations

Bisection method result: 7.450580843640056e-10


### **2. Implementing Newton’s Method**
Newton’s Method is a fast, **quadratic convergence** approach for finding roots. It iteratively refines the root approximation using:
$$
x_{n+1} = x_n - \frac{f(x_n)}{f'(x_n)}
$$
where $( f'(x) )$ is the derivative of $( f(x) )$.

For the **cube root function**:
$$
f(x) = \sqrt[3]{x}
$$
its derivative is:
$$
f'(x) = \frac{1}{3 \cdot |x|^{2/3}}
$$

However, $( f'(x) )$ **diverges to infinity at $( x = 0 )$**, which can cause **Newton’s method to fail**.


In [31]:

def fprime(x):
    # Derivative: 1/(3*(|x|^(2/3))).
    # Avoid division by zero.
    if x == 0:
        raise ZeroDivisionError("Derivative undefined at x=0")
    return 1 / (3 * np.cbrt(x**2))

def newton_method(x0, tol=1e-8, max_iter=20):
    x = x0
    print("Newton's Method Iterations:")
    for i in range(max_iter):
        try:
            fp = fprime(x)
        except ZeroDivisionError:
            print(f"Iteration {i}: Derivative zero at x={x}.")
            return None
        x_new = x - f(x) / fp
        print(f"Iteration {i}: x = {x_new}")
        if abs(x_new - x) < tol:
            print(f"Converged after {i} iterations.")
            return x_new
        x = x_new
    return x

# For f(x) = cbrt(x), the only root is at x = 0.
# Newton's method starting from x0 != 0 will not converge.
x0 = 1.0
newton_root = newton_method(x0)
print("\nNewton's method result:", newton_root)

Newton's Method Iterations:
Iteration 0: x = -2.0
Iteration 1: x = 4.000000000000001
Iteration 2: x = -8.0
Iteration 3: x = 16.0
Iteration 4: x = -32.00000000000001
Iteration 5: x = 64.0
Iteration 6: x = -128.0
Iteration 7: x = 256.00000000000006
Iteration 8: x = -512.0
Iteration 9: x = 1024.0
Iteration 10: x = -2048.0000000000005
Iteration 11: x = 4096.0
Iteration 12: x = -8192.0
Iteration 13: x = 16384.000000000004
Iteration 14: x = -32768.0
Iteration 15: x = 65536.0
Iteration 16: x = -131072.00000000003
Iteration 17: x = 262144.0
Iteration 18: x = -524288.0
Iteration 19: x = 1048576.0000000002

Newton's method result: 1048576.0000000002


## **Newton's Method for Linear Regression**

In this section, we apply **Newton’s Method** to estimate the parameters $( \beta )$ in a **linear regression model**. The goal is to minimize the sum of squared residuals:

$$
\min_{\beta} \| X\beta - y \|^2
$$

where:
- $( X )$ is an $( m \times n )$ matrix of input features.
- $( \beta )$ is an $( n \times 1 )$ vector of unknown parameters.
- $( y )$ is an $( m \times 1 )$ vector of observed target values.



In [33]:
np.random.seed(42)
m, n = 100, 3
X = np.random.rand(m, n)
true_beta = np.array([3,5,6])
y = X @ true_beta + np.random.randn(m)*0.1

## **Implementing Newton’s Method**

### **Algorithm for Newton’s Method in Linear Regression**
Newton’s Method iteratively updates the estimate of $ \beta $ using the formula:

$$
\beta_{k+1} = \beta_k - H^{-1} \nabla L(\beta_k)
$$

For **linear least squares regression**, the loss function is:

$$
L(\beta) = \frac{1}{2} \|X\beta - y\|^2
$$

- **Gradient (First Derivative):**
  $$
  \nabla L(\beta) = X^T (X\beta - y)
  $$
- **Hessian (Second Derivative):**
  $$
  H = X^T X
  $$

Since this is a **quadratic loss function**, Newton’s update rule becomes:

$$
\beta_{k+1} = \beta_k - (X^T X)^{-1} X^T (X\beta_k - y)
$$

This means that Newton’s update step is equivalent to solving for $\beta$ using the **normal equation**.


### **Why Converge in one step?**
Since the Newton update step is:

$$
\beta_{new} = \beta - (X^T X)^{-1} X^T (X\beta - y)
$$

If we start at $ \beta = 0 $:

$$
\beta_{new} = - (X^T X)^{-1} X^T (-y)
$$

$$
\beta_{new} = (X^T X)^{-1} X^T y
$$

which is the **closed-form solution for linear regression** using the normal equation:

$$
\beta^* = (X^T X)^{-1} X^T y
$$

Thus, Newton’s method **immediately finds the optimal solution in one step**.



In [34]:

def Newton_method(tol=1e-8, max_iter=20):
    beta = np.zeros(n)
    for i in range(max_iter):
        print(f"{i} iteration: beta = {beta}")
        gradient = X.T @ (X @ beta - y)
        hessian = X.T @ X
        beta -= np.linalg.solve(hessian, gradient)
        if np.linalg.norm(gradient) < tol:
            return beta

    print("Newton's method did not converge.")
    return beta

beta = Newton_method()
# print("Estimated beta:", beta)
print("True beta:", true_beta)


0 iteration: beta = [1. 1. 1.]
1 iteration: beta = [3.01124533 4.97041046 6.03920518]
True beta: [3 5 6]


## **Newton's Method for Logistic Regression**

This session explains the implementation of **Newton's Method** for **logistic regression**, including:
- How the **Hessian matrix** is computed.
- Why the **condition number of the Hessian** is checked.

---



### **1. Sigmoid Function**
The **sigmoid function** is used to transform linear outputs into probabilities:

$$
\sigma(z) = \frac{1}{1 + e^{-z}}
$$


It maps any real number to the range $ (0,1) $, ensuring that outputs can be interpreted as probabilities.

---

### **2. Logistic regression**
Logistic regression models the probability of class **$ y = 1 $** given input **$ X $** using the **sigmoid function**:

$$
P(y = 1 | X) = \sigma(X\theta) = \frac{1}{1 + e^{-X\theta}}
$$

Given a dataset with $ m $ samples and $ n $ features, we assume that each label $ y_i $ is generated independently according to the Bernoulli distribution:

$$
y_i \sim \text{Bernoulli}(\sigma(X_i^T \theta))
$$

This means the probability mass function (PMF) for each sample is:

$$
P(y_i | X_i, \theta) = \sigma(X_i^T \theta)^{y_i} (1 - \sigma(X_i^T \theta))^{(1 - y_i)}
$$

The **likelihood function** for the entire dataset, assuming **independent observations**, is the product of individual sample probabilities:

$$
L(\theta) = \prod_{i=1}^{m} P(y_i | X_i, \theta)
= \prod_{i=1}^{m} \sigma(X_i^T \theta)^{y_i} (1 - \sigma(X_i^T \theta))^{(1 - y_i)}
$$

Since likelihood functions are often more convenient to work with in **log space**, we take the **log-likelihood**:

$$
\ell(\theta) = \log L(\theta) = \sum_{i=1}^{m} \left[ y_i \log \sigma(X_i^T \theta) + (1 - y_i) \log (1 - \sigma(X_i^T \theta)) \right]
$$

where:
- $ \sigma(X_i^T \theta) $ is the predicted probability of $ y_i = 1 $.
- $ \log \sigma(X_i^T \theta) $ measures confidence in classifying positive samples correctly.
- $ \log (1 - \sigma(X_i^T \theta)) $ measures confidence in classifying negative samples correctly.

Thus, **maximizing the log-likelihood function** corresponds to **maximizing the probability of observing the given labels** under the logistic regression model.


---
### **3. Gradient Computation**
To apply **Newton’s method**, we first compute the **gradient** of $ L(\theta) $ with respect to $ \theta $:

$$
\nabla L(\theta) = \sum_{i=1}^{m} \left[ y_i - \sigma(X_i^T \theta) \right] X_i
$$

which can be rewritten in **matrix form** as:

$$
\nabla L(\theta) = X^T (y - h)
$$

where:
- $ X $ is the $ m \times n $ **feature matrix**.
- $ y $ is the $ m \times 1 $ **vector of actual labels**.
- $ h = \sigma(X\theta) $ is the $ m \times 1 $ **vector of predicted probabilities**.


---

### **4. Hessian Matrix Computation**
The **Hessian matrix** is the second derivative of the **log-likelihood function** with respect to $ \theta $:

$$
H = \frac{\partial^2 L(\theta)}{\partial \theta^2}
$$

Since the gradient is:

$$
\nabla L(\theta) = X^T (y - h)
$$

We differentiate again:

$$
H = \frac{\partial}{\partial \theta} \left[ X^T (y - h) \right]
$$

Since $ y $ is constant with respect to $ \theta $, we only need to differentiate $ -X^T h $, where:

$$
h = \sigma(X\theta)
$$

Using the **derivative of the sigmoid function**:

$$
\frac{d\sigma(z)}{dz} = \sigma(z) (1 - \sigma(z))
$$

Applying the chain rule:

$$
\frac{\partial h}{\partial \theta} = \text{diag} (h \odot (1 - h)) X
$$

where $ \odot $ represents element-wise multiplication.

Thus, differentiating again:

$$
H = -X^T \left[ \text{diag} (h \odot (1 - h)) X \right]
$$

which simplifies to:

$$
H = X^T R X
$$

where $ R $ is the **diagonal matrix**:

$$
R_{ii} = h_i (1 - h_i) = \sigma(X_i^T \theta) (1 - \sigma(X_i^T \theta))
$$

This is the **Hessian matrix for logistic regression**.

---

## **5. Checking Hessian Condition Number**
The **condition number** of $ H $ is computed to determine numerical stability:

$$
\text{condition number} = \frac{\lambda_{\max}}{\lambda_{\min}}
$$

where $ \lambda_{\max} $ and $ \lambda_{\min} $ are the **largest and smallest eigenvalues** of $ H $. 

A **high condition number** indicates:
- The Hessian is **ill-conditioned**.
- **Large numerical errors** may occur when inverting $ H $.

If the **condition number is too high**, the optimization might fail.




In [40]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def newton_method(X, y, tol=1e-6, max_iter=20):
    m, n = X.shape
    theta = np.zeros(n)  # initialize guess at 0
    
    for i in range(max_iter):
        h = sigmoid(X @ theta)
        
        # get gradient and Hessian matrix
        gradient = X.T @ (y - h)
        
        R = np.diag(h * (1 - h))  # m x m diagonal matrix
        H = X.T @ R @ X  # Hessian matrix

        condition_number = np.linalg.cond(H)
        print(f"Hessian condition number for {i+1}th iterations:", condition_number)

        # update theta
        try:
            delta_theta = np.linalg.solve(H, gradient)  
        except np.linalg.LinAlgError:
            print("Singular matrix error!")
        theta += delta_theta

        # check convergence
        if np.linalg.norm(delta_theta) < tol:
            print(f"Converged in {i+1} iterations.")
            return theta
    
    print("Newton's method did not fully converge.")
    return theta

In [ ]:
# success case
np.random.seed(42)
m, n = 5000, 2 # 100 samples, 2 features
X = np.random.rand(m, n)
true_theta = np.array([3, 5]) # true parameters
y_prob = 1 / (1 + np.exp(-X @ true_theta))  # logistic function
y = (np.random.rand(m) < y_prob).astype(int)  
theta_estimated = newton_method(X, y)
print("Estimated theta:", theta_estimated)

Hessian condition number for 1th iterations: 6.719390237522599
Hessian condition number for 2th iterations: 5.07764089617307
Hessian condition number for 3th iterations: 4.235696970583115
Hessian condition number for 4th iterations: 4.001463243527199
Hessian condition number for 5th iterations: 4.173746458969424
Hessian condition number for 6th iterations: 4.304147668309576
Hessian condition number for 7th iterations: 4.314402827265504
Hessian condition number for 8th iterations: 4.314439671733583
Converged in 8 iterations.
Estimated theta: [2.79584111 4.97753775]


In [ ]:
# failure case
np.random.seed(42)
m, n = 5000, 2
X = np.random.rand(m, 1)  
# second feature is twice the first plus 1, so hesse matrix is singular
X = np.hstack([X, 2 * X + 1])  

true_theta = np.array([3, 5])
y_prob = 1 / (1 + np.exp(-X @ true_theta))  
y = (np.random.rand(m) < y_prob).astype(int)

theta_estimated = newton_method(X, y)
print("Estimated theta:", theta_estimated)


Hessian condition number for 1th iterations: 254.794196305102
Hessian condition number for 2th iterations: 254.34604162860165
Hessian condition number for 3th iterations: 253.05370293741206
Hessian condition number for 4th iterations: 249.56651290247902
Hessian condition number for 5th iterations: 240.5976250581648
Hessian condition number for 6th iterations: 219.7669786371672
Hessian condition number for 7th iterations: 181.88194995153088
Hessian condition number for 8th iterations: 141.6684792059006
Hessian condition number for 9th iterations: 130.72022121990454
Hessian condition number for 10th iterations: 148.6894125377634
Hessian condition number for 11th iterations: 169.38276635851625
Hessian condition number for 12th iterations: 176.1563056138908
Hessian condition number for 13th iterations: 176.57262273954888
Hessian condition number for 14th iterations: 176.57401115639712
Converged in 14 iterations.
Estimated theta: [-3.66805674  5.78143667]


## QR decomposition

In [16]:
import numpy as np

### Gram-Schmidt

In [17]:
def gram_schmidt(A):
    """
    Compute the QR factorization of A using the classical Gram–Schmidt process.
    Returns:
       Q: m x n matrix with orthonormal columns
       R: n x n upper triangular matrix, with A = Q @ R
    """
    m, n = A.shape
    Q = np.zeros((m, n))
    R = np.zeros((n, n))
    for j in range(n):
        v = A[:, j].copy()
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], A[:, j])
            v = v - R[i, j] * Q[:, i]
        R[j, j] = np.linalg.norm(v)
        if np.isclose(R[j, j], 0.0):
            raise ValueError("Matrix A has linearly dependent columns.")
        Q[:, j] = v / R[j, j]
    return Q, R

### Householder

In [18]:
def householder_qr(A):
    """
    Compute the QR factorization of A using Householder reflections.
    Returns:
       Q: m x m orthogonal matrix
       R: m x n upper triangular matrix, with A = Q @ R
    """
    m, n = A.shape
    R = A.copy().astype(float)
    Q = np.eye(m)

    for k in range(min(m, n)):
        # Form the vector to reflect
        x = R[k:, k]
        norm_x = np.linalg.norm(x)
        if np.isclose(norm_x, 0):
            continue
        # Choose sign to avoid cancellation
        sign = -np.sign(x[0]) if x[0] != 0 else -1
        u1 = x[0] - sign * norm_x
        v = x.copy()
        v[0] = u1
        v = v / np.linalg.norm(v)

        # Build the Householder matrix H_k for the submatrix
        Hk = np.eye(m)
        Hk[k:, k:] -= 2.0 * np.outer(v, v)

        R = Hk @ R
        Q = Q @ Hk

    return Q, R

### Given Rotation

In [19]:

def givens_qr(A):
    """
    Compute the QR factorization of A using Givens rotations.
    Returns:
       Q: m x m orthogonal matrix
       R: m x n upper triangular matrix, with A = Q @ R
    """
    m, n = A.shape
    R = A.copy().astype(float)
    Q = np.eye(m)

    # Process each column
    for j in range(n):
        # Zero out the entries below the diagonal in column j
        for i in range(j+1, m):
            a = R[j, j]
            b = R[i, j]
            r = np.hypot(a, b)
            if np.isclose(r, 0):
                continue
            c = a / r
            s = b / r
            # Apply rotation to R: update rows j and i for columns j:n
            for k in range(j, n):
                temp = c * R[j, k] + s * R[i, k]
                R[i, k] = -s * R[j, k] + c * R[i, k]
                R[j, k] = temp
            # Apply rotation to Q: update columns j and i of Q
            temp_j = Q[:, j].copy()
            temp_i = Q[:, i].copy()
            Q[:, j] = c * temp_j + s * temp_i
            Q[:, i] = -s * temp_j + c * temp_i
    return Q, R


In [20]:

# Main script to compute and compare QR factorizations
if __name__ == "__main__":
    np.random.seed(0)
    A = np.random.randn(4, 3)

    print("Matrix A:")
    print(A)

    # 1. Gram-Schmidt QR factorization (reduced Q: m x n)
    Q_gs, R_gs = gram_schmidt(A)
    print("\n--- Gram-Schmidt QR Factorization ---")
    print("Q (Gram-Schmidt):")
    print(Q_gs)
    print("R (Gram-Schmidt):")
    print(R_gs)
    print("Reconstruction (Q_gs @ R_gs):")
    print(Q_gs @ R_gs)

    # 2. Householder QR factorization (full Q: m x m)
    Q_h_full, R_h = householder_qr(A)
    # Extract the first n columns for comparison
    Q_h = Q_h_full[:, :A.shape[1]]
    print("\n--- Householder QR Factorization ---")
    print("Q (Householder, reduced to first n columns):")
    print(Q_h)
    print("R (Householder):")
    print(R_h)
    print("Reconstruction (Q_h_full @ R_h):")
    print(Q_h_full @ R_h)

    # 3. Givens QR factorization (full Q: m x m)
    Q_giv_full, R_giv = givens_qr(A)
    # Extract the first n columns for comparison
    Q_giv = Q_giv_full[:, :A.shape[1]]
    print("\n--- Givens QR Factorization ---")
    print("Q (Givens, reduced to first n columns):")
    print(Q_giv)
    print("R (Givens):")
    print(R_giv)
    print("Reconstruction (Q_giv_full @ R_giv):")
    print(Q_giv_full @ R_giv)

    # Compare the Q matrices column by column (up to a possible sign change)
    n = A.shape[1]
    def same_up_to_sign(u, v):
        return np.allclose(u, v) or np.allclose(u, -v)

    print("\n--- Column-by-Column Comparison of Q (up to sign differences) ---")
    for i in range(n):
        col_gs = Q_gs[:, i]
        col_hh = Q_h[:, i]
        col_giv = Q_giv[:, i]
        print(f"\nColumn {i}:")
        print("Gram-Schmidt vs. Householder:", "Agree" if same_up_to_sign(col_gs, col_hh) else "Differ")
        print("Gram-Schmidt vs. Givens:", "Agree" if same_up_to_sign(col_gs, col_giv) else "Differ")


Matrix A:
[[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]
 [ 0.95008842 -0.15135721 -0.10321885]
 [ 0.4105985   0.14404357  1.45427351]]

--- Gram-Schmidt QR Factorization ---
Q (Gram-Schmidt):
[[ 0.581441   -0.47915974  0.25929548]
 [ 0.73861028  0.64154205 -0.15752491]
 [ 0.31315418 -0.59551882 -0.46848788]
 [ 0.13533544 -0.06470756  0.82974144]]
R (Gram-Schmidt):
[[ 3.0339318   1.58416139  0.01174224]
 [ 0.          1.08719312 -1.12857042]
 [ 0.          0.          1.66275572]]
Reconstruction (Q_gs @ R_gs):
[[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]
 [ 0.95008842 -0.15135721 -0.10321885]
 [ 0.4105985   0.14404357  1.45427351]]

--- Householder QR Factorization ---
Q (Householder, reduced to first n columns):
[[-0.581441    0.47915974  0.25929548]
 [-0.73861028 -0.64154205 -0.15752491]
 [-0.31315418  0.59551882 -0.46848788]
 [-0.13533544  0.06470756  0.82974144]]
R (Householder):
[[-3.03393180e+00 -1.58416139e+00 -1.17